{"uuid":"4ceb883a-97fc-4d19-a8ae-8d83a305bfc1","historyId":"6727cf18f1ae931fb9b26ec0d9fe1356","fullName":"PersonMapperTest.testInsertPerson","labels":[{"name":"package","value":"PersonMapperTest"},{"name":"testClass","value":"PersonMapperTest"},{"name":"testMethod","value":"testInsertPerson"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"rest-assured-homework"},{"name":"subSuite","value":"PersonMapperTest"},{"name":"host","value":"EJOI-2"},{"name":"thread","value":"17360@EJOI-2.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"testInsertPerson","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"\r\n### Error updating database.  Cause: org.h2.jdbc.JdbcSQLSyntaxErrorException: Column \"birthDate\" not found; SQL statement:\nINSERT INTO employee (name, department, phone, address, salary, email, birthDate) VALUES (?, ?, ?, ?, ?, ?, ?) [42122-224]\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:514)\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:489)\r\n\tat org.h2.message.DbException.get(DbException.java:223)\r\n\tat org.h2.message.DbException.get(DbException.java:199)\r\n\tat org.h2.table.Table.getColumn(Table.java:759)\r\n\tat org.h2.command.Parser.parseColumn(Parser.java:1190)\r\n\tat org.h2.command.Parser.parseColumnList(Parser.java:1175)\r\n\tat org.h2.command.Parser.parseInsert(Parser.java:1549)\r\n\tat org.h2.command.Parser.parsePrepared(Parser.java:719)\r\n\tat org.h2.command.Parser.parse(Parser.java:592)\r\n\tat org.h2.command.Parser.parse(Parser.java:564)\r\n\tat org.h2.command.Parser.prepareCommand(Parser.java:483)\r\n\tat org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:639)\r\n\tat org.h2.server.TcpServerThread.process(TcpServerThread.java:289)\r\n\tat org.h2.server.TcpServerThread.run(TcpServerThread.java:191)\r\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\r\n\r\n### The error may exist in db/mapper/EmployeeMapper.java (best guess)\r\n### The error may involve db.mapper.EmployeeMapper.insertEmployee\r\n### The error occurred while executing an update\r\n### SQL: INSERT INTO employee (name, department, phone, address, salary, email, birthDate) VALUES (?, ?, ?, ?, ?, ?, ?)\r\n### Cause: org.h2.jdbc.JdbcSQLSyntaxErrorException: Column \"birthDate\" not found; SQL statement:\nINSERT INTO employee (name, department, phone, address, salary, email, birthDate) VALUES (?, ?, ?, ?, ?, ?, ?) [42122-224]\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:514)\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:489)\r\n\tat org.h2.message.DbException.get(DbException.java:223)\r\n\tat org.h2.message.DbException.get(DbException.java:199)\r\n\tat org.h2.table.Table.getColumn(Table.java:759)\r\n\tat org.h2.command.Parser.parseColumn(Parser.java:1190)\r\n\tat org.h2.command.Parser.parseColumnList(Parser.java:1175)\r\n\tat org.h2.command.Parser.parseInsert(Parser.java:1549)\r\n\tat org.h2.command.Parser.parsePrepared(Parser.java:719)\r\n\tat org.h2.command.Parser.parse(Parser.java:592)\r\n\tat org.h2.command.Parser.parse(Parser.java:564)\r\n\tat org.h2.command.Parser.prepareCommand(Parser.java:483)\r\n\tat org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:639)\r\n\tat org.h2.server.TcpServerThread.process(TcpServerThread.java:289)\r\n\tat org.h2.server.TcpServerThread.run(TcpServerThread.java:191)\r\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\r\n","trace":"org.apache.ibatis.exceptions.PersistenceException: \r\n### Error updating database.  Cause: org.h2.jdbc.JdbcSQLSyntaxErrorException: Column \"birthDate\" not found; SQL statement:\nINSERT INTO employee (name, department, phone, address, salary, email, birthDate) VALUES (?, ?, ?, ?, ?, ?, ?) [42122-224]\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:514)\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:489)\r\n\tat org.h2.message.DbException.get(DbException.java:223)\r\n\tat org.h2.message.DbException.get(DbException.java:199)\r\n\tat org.h2.table.Table.getColumn(Table.java:759)\r\n\tat org.h2.command.Parser.parseColumn(Parser.java:1190)\r\n\tat org.h2.command.Parser.parseColumnList(Parser.java:1175)\r\n\tat org.h2.command.Parser.parseInsert(Parser.java:1549)\r\n\tat org.h2.command.Parser.parsePrepared(Parser.java:719)\r\n\tat org.h2.command.Parser.parse(Parser.java:592)\r\n\tat org.h2.command.Parser.parse(Parser.java:564)\r\n\tat org.h2.command.Parser.prepareCommand(Parser.java:483)\r\n\tat org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:639)\r\n\tat org.h2.server.TcpServerThread.process(TcpServerThread.java:289)\r\n\tat org.h2.server.TcpServerThread.run(TcpServerThread.java:191)\r\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\r\n\r\n### The error may exist in db/mapper/EmployeeMapper.java (best guess)\r\n### The error may involve db.mapper.EmployeeMapper.insertEmployee\r\n### The error occurred while executing an update\r\n### SQL: INSERT INTO employee (name, department, phone, address, salary, email, birthDate) VALUES (?, ?, ?, ?, ?, ?, ?)\r\n### Cause: org.h2.jdbc.JdbcSQLSyntaxErrorException: Column \"birthDate\" not found; SQL statement:\nINSERT INTO employee (name, department, phone, address, salary, email, birthDate) VALUES (?, ?, ?, ?, ?, ?, ?) [42122-224]\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:514)\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:489)\r\n\tat org.h2.message.DbException.get(DbException.java:223)\r\n\tat org.h2.message.DbException.get(DbException.java:199)\r\n\tat org.h2.table.Table.getColumn(Table.java:759)\r\n\tat org.h2.command.Parser.parseColumn(Parser.java:1190)\r\n\tat org.h2.command.Parser.parseColumnList(Parser.java:1175)\r\n\tat org.h2.command.Parser.parseInsert(Parser.java:1549)\r\n\tat org.h2.command.Parser.parsePrepared(Parser.java:719)\r\n\tat org.h2.command.Parser.parse(Parser.java:592)\r\n\tat org.h2.command.Parser.parse(Parser.java:564)\r\n\tat org.h2.command.Parser.prepareCommand(Parser.java:483)\r\n\tat org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:639)\r\n\tat org.h2.server.TcpServerThread.process(TcpServerThread.java:289)\r\n\tat org.h2.server.TcpServerThread.run(TcpServerThread.java:191)\r\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\r\n\r\n\tat org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)\r\n\tat org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:199)\r\n\tat org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)\r\n\tat org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)\r\n\tat org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:141)\r\n\tat org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)\r\n\tat jdk.proxy2/jdk.proxy2.$Proxy15.insertEmployee(Unknown Source)\r\n\tat PersonMapperTest.testInsertPerson(PersonMapperTest.java:28)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1596)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:739)\r\n\tat org.testng.TestRunner.run(TestRunner.java:614)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\nCaused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Column \"birthDate\" not found; SQL statement:\nINSERT INTO employee (name, department, phone, address, salary, email, birthDate) VALUES (?, ?, ?, ?, ?, ?, ?) [42122-224]\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:514)\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:489)\r\n\tat org.h2.message.DbException.get(DbException.java:223)\r\n\tat org.h2.message.DbException.get(DbException.java:199)\r\n\tat org.h2.table.Table.getColumn(Table.java:759)\r\n\tat org.h2.command.Parser.parseColumn(Parser.java:1190)\r\n\tat org.h2.command.Parser.parseColumnList(Parser.java:1175)\r\n\tat org.h2.command.Parser.parseInsert(Parser.java:1549)\r\n\tat org.h2.command.Parser.parsePrepared(Parser.java:719)\r\n\tat org.h2.command.Parser.parse(Parser.java:592)\r\n\tat org.h2.command.Parser.parse(Parser.java:564)\r\n\tat org.h2.command.Parser.prepareCommand(Parser.java:483)\r\n\tat org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:639)\r\n\tat org.h2.server.TcpServerThread.process(TcpServerThread.java:289)\r\n\tat org.h2.server.TcpServerThread.run(TcpServerThread.java:191)\r\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\r\n\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:514)\r\n\tat org.h2.engine.SessionRemote.readSQLException(SessionRemote.java:663)\r\n\tat org.h2.engine.SessionRemote.readException(SessionRemote.java:646)\r\n\tat org.h2.engine.SessionRemote.done(SessionRemote.java:620)\r\n\tat org.h2.command.CommandRemote.prepare(CommandRemote.java:84)\r\n\tat org.h2.command.CommandRemote.<init>(CommandRemote.java:56)\r\n\tat org.h2.engine.SessionRemote.prepareCommand(SessionRemote.java:488)\r\n\tat org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1164)\r\n\tat org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:93)\r\n\tat org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:1092)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.apache.ibatis.datasource.pooled.PooledConnection.invoke(PooledConnection.java:258)\r\n\tat jdk.proxy3/jdk.proxy3.$Proxy9.prepareStatement(Unknown Source)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.apache.ibatis.logging.jdbc.ConnectionLogger.invoke(ConnectionLogger.java:53)\r\n\tat jdk.proxy3/jdk.proxy3.$Proxy9.prepareStatement(Unknown Source)\r\n\tat org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:82)\r\n\tat org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:90)\r\n\tat org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:60)\r\n\tat org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:90)\r\n\tat org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:49)\r\n\tat org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)\r\n\tat org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)\r\n\tat org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)\r\n\t... 31 more\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1738354291993,"stop":1738354292496}